apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-pod
  template:
    metadata:
      labels:
        app: master-pod
    spec:
      containers:
      - name: master-container
        image: ibitec/master-pod:master4
        env:
        - name: BOOTSTRAP_SERVERS
          value: kafka.default.svc.cluster.local:9092
        volumeMounts:
        - name: master-config
          mountPath: /app/src
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: master-config
        configMap:
          name: master-config
