apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
      - name: node-container
        image: ibitec/node-pod:node4
        env:
        - name: BOOTSTRAP_SERVERS
          value: kafka.default.svc.cluster.local:9092
        volumeMounts:
        - name: node-config
          mountPath: /app/src
        resources:
          requests:
            memory: "4Gi"   
            cpu: "2"        
          limits:
            memory: "6Gi"   
            cpu: "3"       
      volumes:
      - name: node-config
        configMap:
          name: node-config
