apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config

data:
  config.yaml: |
    consumer:
      server: "kafka.default.svc.cluster.local:9092"
      autocommit: "false"
      autooffset: "earliest"
      acks: "1"

    producer:
      server: "kafka.default.svc.cluster.local:9092"
      autocommit: "false"
      batchsize: "64000"
      lingerms: "10"
      compressiontype: "lz4"
      acks: "1"

    performance:
      tx_time: 5
      timeout: 10
      block_size: 512
